version: '3.8'
services:
  web:
    image: nginx:latest
    container_name: web_server
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:

